// <auto-generated />
namespace BusinessCredit.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemovedAccruindOverduePenalty_DontNeedIt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovedAccruindOverduePenalty_DontNeedIt));
        
        string IMigrationMetadata.Id
        {
            get { return "201506281117454_RemovedAccruindOverduePenalty_DontNeedIt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
