// <auto-generated />
namespace BusinessCredit.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LoanCurrentDebt_and_LoanWholeDebt_Changed_to_methods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoanCurrentDebt_and_LoanWholeDebt_Changed_to_methods));
        
        string IMigrationMetadata.Id
        {
            get { return "201506120816501_LoanCurrentDebt_and_LoanWholeDebt_Changed_to_methods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
