// <auto-generated />
namespace BusinessCredit.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Temporary_DbModel_Change__Payments_Added_Setters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Temporary_DbModel_Change__Payments_Added_Setters));
        
        string IMigrationMetadata.Id
        {
            get { return "201506111156052_Temporary_DbModel_Change__Payments_Added_Setters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
