// <auto-generated />
namespace BusinessCredit.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agreement_Object_To_String_Object : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agreement_Object_To_String_Object));
        
        string IMigrationMetadata.Id
        {
            get { return "201506120737069_Agreement_Object_To_String_Object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
