// <auto-generated />
namespace BusinessCredit.LoanManagementSystem.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Enabled_Keys_Autogenerate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Enabled_Keys_Autogenerate));
        
        string IMigrationMetadata.Id
        {
            get { return "201506161138039_Enabled_Keys_Autogenerate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
