// <auto-generated />
namespace BusinessCredit.LoanManagementSystem.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class After_Splitting_By_Branches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(After_Splitting_By_Branches));
        
        string IMigrationMetadata.Id
        {
            get { return "201506130916200_After_Splitting_By_Branches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
